### ISSUE TITLE
Could not find net.corda:corda-core:0.16-SNAPSHOT

### ISSUE THREAD

**Issue by lakshmikumarn** [corda/cordapp-example#115]
Running ./gradlew deployNodes throws the below error

* What went wrong:
A problem occurred evaluating project ':java-source'.
> Could not resolve all files for configuration ':java-source:runtime'.
   > Could not find net.corda:corda-core:0.16-SNAPSHOT.
     Searched in the following locations:

**Comment by joeldudleyr3** [comment]
This happens if you check out the master branch without installing Corda locally first. See https://docs.corda.net/building-against-master.html.
